---
# See the documentation for more information:
# https://packit.dev/docs/configuration/

downstream_package_name: podman
upstream_tag_template: v{version}

packages:
  podman-rhel:
    specfile_path: rpm/podman.spec

srpm_build_deps:
  - git-archive-all
  - make

actions:
  fix-spec-file:
    - "bash .packit.sh"

jobs:
  - job: copr_build
    trigger: pull_request
    packages: [podman-rhel]
    notifications:
      failure_comment:
        message: "Ephemeral COPR build failed. @containers/packit-build please check."
    enable_net: true
    targets:
      - epel-9-x86_64
      - epel-9-aarch64
